In [4]:
from  src.cyto.helpers import *
import src.cyto.pipeline
from  src.cyto.grouping import *
from  src.cyto.pipeline import *
from  src.cyto.visualization import *
from importlib import reload
reload(src.cyto.pipeline)
reload(src.cyto.grouping)


<module 'src.cyto.grouping' from 'C:\\Users\\Muhammad_Saeed\\PycharmProjects\\flowcyto_alignment\\src\\cyto\\grouping.py'>

In [5]:
print('here')

here


In [6]:


path = '../../data/080322-ENU-Mouse-Normalisation-Data-Gated.csv'

X, Y, columns_names = load_data(path)

In [7]:
pipeline = Pipeline(X, Y, 15, channel_names=columns_names)


In [8]:
%matplotlib qt

In [9]:
print(columns_names)

['sample_code', 'FSC-A', 'FSC-H', 'FSC-W', 'SSC-A', 'SSC-H', 'SSC-W', 'FITC-A', 'PE-A', 'PerCP-Cy5-5-A', 'PE-Cy7-A', 'Alexa 405 / Pac Blue-A', 'Qdot 605-A', 'APC-A', 'Alexa Fluor 700-A', 'APC-Alexa 750 / APC-Cy7-A', 'Time', 'Event-ID']


In [10]:
pipeline.segment_data()

****
****
****
****
 Sample: 0 ****
****
****
****

0.04 0.16 0.23
bounds [[-0.06019178513381404, 0.9516547887102804]]
tightened_bounds [[0.13056765039868998, 0.7541618513646265]]
0.04 0.16 0.23
bounds [[-0.110064294921875, 0.9116974357304789]]
tightened_bounds [[0.09713725430116588, 0.6523018706049973]]
0.04 0.16 0.23
bounds [[-0.044664160747411724, 1.1152219169743773]]
tightened_bounds [[0.3308396462173674, 0.8993904400607955]]
0.04 0.16 0.23
bounds [[-0.03965550466756676, 0.8427185021898683]]
tightened_bounds [[0.12788366898887307, 0.6712957155319412]]
0.04 0.16 0.23
bounds [[-0.045800032517254154, 0.7859718314236865]]
tightened_bounds [[0.13244242577730908, 0.4722197265665543]]
0.04 0.16 0.23
bounds [[0.007697560937830736, 0.9025668978437915]]
tightened_bounds [[0.09902747354355187, 0.3503858481054943]]
0.04 0.16 0.23
bounds [[0.000851657297374242, 1.0962236459198282]]
tightened_bounds [[0.3890843545266165, 0.7917718669883839]]
width 0.395 depth 0.8785568878066736 width_cond False


In [16]:
ch =10
print(columns_names[ch+1])
plot_channel_segments(ch, pipeline.samples, show_labels=False, limit_x0=-.2, limit_x1=1.2)

Alexa 405 / Pac Blue-A


In [15]:
pipeline.resegment_channel(ch,width_threshold=0.02,
                           area_threshold=.005, depth_threshold=.02)

In [17]:
pipeline.commit_changes()

In [18]:
plot_channel_segments(10, pipeline.samples,limit_x0=-.2, limit_x1=1.2, show_labels=False)

In [19]:
plot_gate_as_tiles(pipeline.data_handler, 10)

In [21]:
pipeline.recompute_and_update_location_hierarchy_and_refs(channels=[10] ,
                                                          jaccard_thresholds= .6)

ch 10
here
Unique groups [1 2 3 4 5] 


[[38.  1.  0. 38.  1.]
 [ 1.  3.  0.  3.  0.]
 [ 0.  0.  1.  1.  0.]
 [38.  3.  1. 60.  2.]
 [ 1.  0.  0.  2.  2.]]
[1, 2]
[1, 4]
[1, 5]
[2, 4]
[3, 4]
[4, 5]
optimal gates:
(1, 9, 0.0) [0.20764862107856397, 0.5282573778404851]
(2, 2, 0.0) [0.7993510151743822, 0.9907236677709321]
(3, 57, 0.0) [0.6830963910035683, 0.9501531017082633]
(4, 0, 0.0) [0.15750657304879848, 1.0347344330243313]
(5, 23, 0.0) [0.7773628094940622, 0.9388829498949344]
constraints [[1, 2], [1, 4], [1, 5], [2, 4], [3, 4], [4, 5]]
iter 0 [[1, 2], [1, 4], [1, 5], [2, 4], [3, 4], [4, 5]]
1.0 4
iter 1 [[1, 2], [1, 4], [1, 5], [2, 4], [4, 5]]
loosened_groups_for_deadlock_dict[10] [([3, 4], <function binary_overlap_constarint at 0x00000212A4D42A60>)]


In [ ]:
plot_gate_as_tiles(pipeline.data_handler, 11, pipeline.Loc_Ref_Dict_All_Ch)

In [22]:
plot_gates_dendrogram(pipeline.agg_models_dict[10], 10, pipeline.jaccard_thresholds[10])

In [ ]:
plot_gate_as_tiles(pipeline.data_handler, 10, pipeline.Loc_Ref_Dict_All_Ch)
ch = 10
plot_gates_dendrogram(pipeline.agg_models_dict[ch], ch, jacc_threshold=pipeline.jaccard_thresholds[ch])
plot_network_graph(10,pipeline.incidence_matrices[10], columns_names)

In [ ]:
pipeline.commit_changes()

In [ ]:
pipeline.update_morphology_hierarchy_and_refs(channels=[0,1,2,10,11,13],
                                              wass_dist_threshold=1e-9)


In [ ]:
pipeline.commit_changes()

In [ ]:
pipeline.align_samples([11,13], sigma = 1)


In [ ]:
plot_scatter_aligned_vs_original([[11,13]],pipeline, columns_names=pipeline.channel_names)


In [ ]:
plot_scatter_aligned_vs_original([[11,13]],pipeline, columns_names=pipeline.channel_names)



In [ ]:
plot_scatter_aligned_vs_original([[11,13]],pipeline, columns_names=pipeline.channel_names)


In [ ]:
pipeline.commit_changes()

In [ ]:
pipeline.clean_and_export()

In [ ]:
reload(src.cyto.pipeline)
pipeline = src.cyto.pipeline.Pipeline(X, Y, 15, channel_names=columns_names, segment_data=True)

In [ ]:
pipeline.end_to_end_align(channels=[13, 12], area_thresholds=[.04, .003],width_thresholds=.2, depth_thresholds=.2,
                          kde_windows=.28,jaccard_thresholds=.6, wass_dist_thresholds=1e-9,verbose=False
                          )

In [ ]:
plot_gate_as_tiles(pipeline.data_handler, 12)

In [ ]:
def assign_location_and_morphology_groups_from_JM(JM, ref_gates, targ_gates,
                                                  jaccard_threshold,
                                                  wass_dist_threshold, wass_n_samples):

    '''

    :param JM:
    :param ref_gates:
    :param targ_gates:
    :param jaccard_threshold:
    :param wass_dist_threshold:
    :param wass_n_samples:
    :return:
    '''

    for i in range(JM.shape[0]):
        # get most overlapping gate
        max_indx = JM.argmax()
        r, c = max_indx//JM.shape[1], max_indx%JM.shape[1]
        max_value = JM[r,c]
        if max_value >= jaccard_threshold:
            # Location
            targ_gates[r].location_group = c+1
            JM[r, :], JM[:, c] = -1, -1

            # morphology
            z1 = ref_gates[c].segment
            z2 = targ_gates[r].segment
            ind1 = np.random.randint(0, z1.shape[0], np.minimum(wass_n_samples, z1.shape[0]))
            ind2 = np.random.randint(0, z2.shape[0], np.minimum(wass_n_samples, z2.shape[0]))

            wd = morphology_distance(z1[ind1], z2[ind2])
            if wd <= wass_dist_threshold:
                targ_gates[r].morphology_group = 1
        else:
            # even the current maximum is lower than the threshold!
            break

def set_references_manually(channels, ref_samples,
                            data_handler, jaccard_thresholds,
                            wass_dist_thresholds,
                            Loc_Ref_Dict_All_Ch, Loc_Morph_Ref_Dict_All_Ch, wass_n_samples=2000
                            ):

    '''

    :param channels:
    :param ref_samples:
    :param data_handler:
    :param jaccard_thresholds:
    :param wass_dist_thresholds:
    :param Loc_Ref_Dict_All_Ch:
    :param Loc_Morph_Ref_Dict_All_Ch:
    :param wass_n_samples:
    :return:
    '''

    # check input
    jaccard_thresholds =  [jaccard_thresholds]*len(channels) if isinstance(jaccard_thresholds, float) else jaccard_thresholds
    wass_dist_thresholds =  [wass_dist_thresholds]*len(channels) if isinstance(wass_dist_thresholds, float) else wass_dist_thresholds
    ref_samples =  [ref_samples]*len(channels) if isinstance(ref_samples, int) else ref_samples

    for ind, ch in enumerate(channels):

        ref_sample = ref_samples[ind]
        ref_gates = data_handler.samples[ref_sample].gates[ch]
        jaccard_threshold, wass_dist_threshold = jaccard_thresholds[ind], wass_dist_thresholds[ind]

        gates_indx_dict = data_handler.get_gates_of_channel_dictionary_indexed_by_sample_num(ch)
        # build partial similarity matrix
        p_sim_matrix = build_similarity_matrix(data_handler.get_gates_of_channel(ch), partial_columns=gates_indx_dict[ref_sample])

        # assign location and morphology groups for every gate
        for samp_num, target_gates_indx in gates_indx_dict.items():
            JM = p_sim_matrix[target_gates_indx, :]
            targ_gates = data_handler.samples[samp_num].gates[ch]
            assign_location_and_morphology_groups_from_JM(JM, ref_gates, targ_gates, jaccard_threshold, wass_dist_threshold, wass_n_samples)

        # fill reference dictionaries
        Loc_Ref_Dict_All_Ch[ch] = {ref.location_group: ref for ref in ref_gates}
        Ref_Dict_indx_by_Loc_and_Morph = {}
        for group, ref in Loc_Ref_Dict_All_Ch[ch].items():
            ref.is_location_reference = True
            Ref_Dict_indx_by_Loc_and_Morph[group, 1] = ref

        Loc_Morph_Ref_Dict_All_Ch[ch] = Ref_Dict_indx_by_Loc_and_Morph

In [ ]:
Loc_Ref_Dict_All_Ch = {}
Loc_Morph_Ref_Dict_All_Ch = {}
set_references_manually([13,14], 0, pipeline.data_handler, .6,1e-5,Loc_Ref_Dict_All_Ch, Loc_Morph_Ref_Dict_All_Ch,
                        wass_n_samples=2000)

In [ ]:
plot_channel_segments(13, pipeline.samples)

In [ ]:
pipeline.recompute_and_update_location_hierarchy_and_refs([13,14],.6)
pipeline.update_morphology_hierarchy_and_refs([13,14],1e-5)

In [ ]:
# quantile test
gates = pipeline.data_handler.get_gates_of_channel(13)
q = .05
start = time.time()
for gate in gates:
    z = gate.segment
    q0, q1 = np.quantile(z,q), np.quantile(z,1-q)
    ind = np.logical_and( gate.t>=gate.gate[0], gate.t<=gate.gate[1])
    gate_ecdf = np.cumsum(gate.pd[ind])/np.sum(gate.pd[ind])
    q00 = gate.t[ind][np.argmin(np.abs(gate_ecdf-q))]
    q11 = gate.t[ind][np.argmin(np.abs(gate_ecdf-(1-q)))]
    print(np.abs(q00-q0), np.abs(q11-q1))

end = time.time()
print(end - start)

In [ ]:
plt.plot(gate.t, gate.pd)

In [ ]:
q0 = np.trapz(gate.pd[ind], gate.t[ind])
print(q0)

In [ ]:
axes = plt.subplots(5,5)[1].flatten()
for i in range(25):
    z = pipeline.samples[i](14)
    t, pdf = pipeline.samples[i].pdfs[14]
    gate_ecdf = np.cumsum(pdf)/np.sum(pdf)
    axes[i].plot(t, gate_ecdf)
    gate_ecdf = sm.distributions.empirical_distribution.ECDF(z)
    t = np.linspace(0, 1, z.shape[0])
    axes[i].plot(t, gate_ecdf(t))

In [ ]:
sns.distplot(gate.segment)
plt.scatter(q0,.2,s=40)
plt.scatter(q00,.2,s=40)

In [ ]:
area_threshold = .05
z = np.concatenate([np.random.normal(0,.05,[2500]),np.random.normal(.8,.05,[2500]),
                    np.random.normal(2.3,.02,[200]),
                    np.random.normal(3.6,.1,[1500])
                    ])
print(z.shape)
kde = sns._statistics.KDE(bw_method=.2)
pdf, t = kde(x1=z.flatten())
plt.plot(t, pdf)
pd_a_s = sk_seg.watershed(-pdf)
plt.scatter(t, pdf, color=list(map(lambda x: colors[x],pd_a_s)))
pd_a_s =  non_maximum_suppression(pdf, pd_a_s, area_threshold = area_threshold)
pd_a_s = merge(pd_a_s)
plt.figure()
plt.scatter(t, pdf, color=list(map(lambda x: colors[x],pd_a_s)))


In [ ]:
pd_a_s1 = sk_seg.watershed(pdf)
plt.scatter(t, pdf, color=list(map(lambda x: colors[x],pd_a_s1)))
pd_a_s2 = sk_seg.watershed(-pdf)
plt.figure()
plt.scatter(t, pdf, color=list(map(lambda x: colors[x],pd_a_s2)))


In [ ]:
plt.scatter(t, -pdf, color=list(map(lambda x: colors[x],np.abs(pd_a_s1-pd_a_s2))))

In [ ]:
def get_valleys(x, pd_seg):
    wl = get_watershed_lines_from_labeled_segs(pd_seg, x)
    # valleys = convert_watershed_lines_to_gate(wl[1:-1])
    valleys = convert_watershed_lines_to_gate(wl)
    return valleys



In [ ]:
def func(x):
    y = np.zeros(x.shape)
    ind = np.logical_and(x>.2, x<=.8)
    y[ind] = 1
    ind = np.logical_and(x>1.3, x<=1.8)
    y[ind] = 2
    ind = np.logical_and(x>1.8, x<=2.2)
    y[ind] = 1.5
    ind = np.logical_and(x>2.2, x<=2.7)
    y[ind] = 2
    ind = np.logical_and(x>3.5, x<=3.65)
    y[ind] = .2
    ind = np.logical_and(x>4.3, x<=5)
    y[ind] = 1
    ind = np.logical_and(x>6.3, x<=6.45)
    y[ind] = .2
    ind = np.logical_and(x>7.5, x<=7.8)
    y[ind] = .2
    return gaussian_filter1d(y,10)

# def func(x):
#     y = np.zeros(x.shape)
#     ind = np.logical_and(x>.2, x<=.8)
#     y[ind] = 1
#     ind = np.logical_and(x>.8, x<=1)
#     y[ind] = .5
#     ind = np.logical_and(x>1, x<=2.2)
#     y[ind] = 1
#     ind = np.logical_and(x>2.2, x<=2.4)
#     y[ind] = .5
#     ind = np.logical_and(x>2.4, x<=3)
#     y[ind] = 1
#     return gaussian_filter1d(y,15)

x = np.linspace(-.5, 8.2,1000)
pdf = func(x)
# pdf = pdf+ np.random.uniform(-.001,.001, pdf.shape)

In [ ]:
pd_a_s = sk_seg.watershed(-pdf)
valleys = get_valleys(x,pd_a_s)

print(len(valleys))

In [ ]:
print(pd_a_s)

In [ ]:
plt.figure()
plt.plot(x, pdf)
for v in valleys:
    ind = np.logical_and(x>v[0], x<=v[1])
    plt.plot(x[ind], pdf[ind])
    plt.axvline(v[0])
plt.axvline(v[1])




In [ ]:
def suppress_and_merge_valleys(pdf, seg_pdf ,pdf_seg_valley, valley_area_threshold):
    seg_pdf_cpy = copy.deepcopy(seg_pdf)
    grid_size_thresh = np.ceil(seg_pdf.shape[0]*.01)
    seg_labels =np.sort( np.unique(seg_pdf_cpy))
    total_area = np.trapz(pdf)
    ind = np.argwhere(np.diff(pdf_seg_valley)).flatten()
    print(seg_labels.shape)
    print(ind.shape)
    for i in range(0, ind.shape[0]-1):
        r = np.trapz(pdf[ind[i]: ind[i+1]].max()-pdf[ind[i]: ind[i+1]])/total_area
        print(r)
        if r <=valley_area_threshold or np.abs(ind[i]- ind[i+1])<grid_size_thresh:
            s = i+1
            print(i, np.abs(ind[i]- ind[i+1]), seg_labels[s], np.count_nonzero(seg_pdf_cpy==s))
            seg_pdf_cpy[seg_pdf_cpy==s] = seg_labels[s]
    seg_labels = np.sort( np.unique(seg_pdf_cpy))
    ord_labels = {s:j+1 for j,s in enumerate(seg_labels)}
    print(seg_pdf_cpy)
    seg_pdf_cpy = np.array(list(map(lambda x:ord_labels[x], seg_pdf_cpy)))
    return seg_pdf_cpy

seg_pdf = copy.deepcopy(pd_a_s)
pdf_seg_valley = sk_seg.watershed(pdf)
seg_pdf = suppress_and_merge_valleys(pdf, seg_pdf, pdf_seg_valley,  .5)

# plt.scatter(x,pdf, c= seg_pdf)

In [ ]:
print(valleys)
# plt.plot(pdf)
plt.figure()
plt.plot(x, pdf)
valleys = get_valleys(x,seg_pdf)
for v in valleys:
    plt.axvline(x=v[0])
plt.axvline(x=v[1])

In [ ]:
total_area = np.trapz(pdf.max()-pdf)
seg_mask = copy.deepcopy(pd_a_s_val)
for s in np.unique(pd_a_s_val):
    # compute the normalized AUC using trapezoid method.
    r = np.trapz(pdf.max()-pdf[seg_mask==s])/total_area
    print(s,r)
    # suppress if r is less than threshold or the segment has less than 2 elements.
    if r <=area_threshold or np.count_nonzero(seg_mask==s)<2:
        seg_mask[seg_mask==s] = 0


In [71]:
%matplotlib qt

def get_smooth_and_monotonic(t, y, div=10):

    '''

    A convolution-based transform to ensure smoothness and monotonicity.

    :param t:
    :param y:
    :return:
    '''

    N = y.shape[0]//div
    # yy =  np.convolve(y, np.ones(N)/N, mode='valid')
    yy, idx = np.unique(y, return_index=True)
    tt = t[idx]
    return np.sort(tt), np.sort(yy), [tt.min(), tt.max()]

In [86]:
z = np.random.uniform(-.5,.5,5000)
for pp in [1000]:
    x = np.linspace(-1,.5,5000)
    y = -2*x**2 + z
    # plt.plot(x,y, alpha=.3)
    x,y,_ = get_smooth_and_monotonic(x, y, div = pp)
    plt.plot(x,y, linewidth=5)
    for dd in [1,20]:
        earth = Earth(max_degree=dd, penalty=.2, smooth=True)
        earth.fit(x,y)
        t = np.linspace(-1, 1, 5000)
        p = earth.predict(t)
        plt.plot(t, p, label=f'{dd}, {pp}', linewidth=1)
plt.legend()

C:\Users\Muhammad_Saeed\anaconda3\lib\site-packages\pyearth\earth.py:813: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  pruning_passer.run()
C:\Users\Muhammad_Saeed\anaconda3\lib\site-packages\pyearth\earth.py:1066: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  coef, resid = np.linalg.lstsq(B, weighted_y[:, i])[0:2]
C:\Users\Muhammad_Saeed\anaconda3\lib\site-packages\pyearth\earth.py:813: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input mat