In [1]:
import seaborn as sns

from ..cyto.helpers import *
from ..cyto.alignment import *
from ..cyto.pipeline import *
from ..cyto.visualization import *
from ..cyto.grouping import *
from ..cyto.segmentation import *
from copy import deepcopy

In [105]:
import numpy as np
import matplotlib.pyplot as plt

z = np.random.normal(0,.4, [2,10000])
z1 = np.concatenate([z,z+2], axis=1)
z2 = .9*z1+.5
z3 = 1.1*z+.2
z4 = 1.1*z+4

sns.distplot(z1, hist=False, kde_kws={'bw_method':.3})
sns.distplot(z2, hist=False, kde_kws={'bw_method':.3})
sns.distplot(z3, hist=False, kde_kws={'bw_method':.3})

C:\Users\Muhammad_Saeed\anaconda3\lib\site-packages\seaborn\distributions.py:2551: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `kdeplot` (an axes-level function for kernel density plots).
  warnings.warn(msg, FutureWarning)
C:\Users\Muhammad_Saeed\anaconda3\lib\site-packages\seaborn\distributions.py:2551: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `kdeplot` (an axes-level function for kernel density plots).
  warnings.warn(msg, FutureWarning)
C:\Users\Muhammad_Saeed\anaconda3\lib\site-packages\seaborn\distributions.py:2551: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with si

<AxesSubplot:ylabel='Density'>

In [106]:
print(z.shape)
print(z1.shape)
print(z2.shape)
print(z3.shape)
print(z4.shape)

(2, 10000)
(2, 20000)
(2, 20000)
(2, 10000)
(2, 10000)


In [107]:
def plot_pdf(z, shift=0, m =1):
    kde = sns._statistics.KDE(bw_method=.3)
    pd, t = kde(x1=z.flatten())
    plt.plot(t, m*pd+shift, c='b')

In [108]:
plot_pdf(z1[0,:], shift=1)
plot_pdf(z2[0,:], shift=.5)
plot_pdf(z3[0,:], shift=0, m=.5)
plot_pdf(z4[0,:], shift=-.5, m=.5)

In [110]:
samples = []
for i, zz in enumerate([z1,z2,z3,z4]):
    s = Sample(zz.T,[-1],i)
    samples+=[s]
data_handler = DataHandler(samples)

width 0.285 depth 0.7039122394281458 width_cond False
0.005 0.2 0.2
bounds [[-2.629982851409088, 1.0181502129482474], [1.0181502129482474, 4.418351903999745]]
tightened_bounds [[-0.7022029084738219, 0.7072255717661627], [1.301041993069059, 2.702491085749553]]
width 0.285 depth 0.7039122394281458 width_cond False
0.005 0.2 0.2
bounds [[-1.8669845662681797, 1.4163351916534224], [1.4163351916534224, 4.4765167135997705]]
tightened_bounds [[-0.13198261762643967, 1.1365030145895465], [1.6709377937621532, 2.9322419771745976]]
0.005 0.2 0.2
bounds [[-2.021236116350326, 2.188442074200048]]
tightened_bounds [[-0.5726534872795389, 0.9714929476180181]]
0.005 0.2 0.2
bounds [[1.7787638836496742, 5.988442074200048]]
tightened_bounds [[3.2273465127204615, 4.771492947618018]]
{0: [(Sample_num: 0, Ch: 0, Gate_num: 0 
Gate: [-2.629, 1.018], Segment_min_max: -1.661, 1.016 
Location_group: 0, Morphology_group: 0, Overall_Indx: 0, Aligned_flag: 0)
, (Sample_num: 0, Ch: 0, Gate_num: 1 
Gate: [1.018, 4.418],

In [523]:
samples.reverse()

In [591]:
plot_channel_segments(0, samples, show_labels=False,limit_x0=-2, limit_x1=6)

In [112]:
Sim_Matrix_dict = {}
agg_models_dict = {}
location_groups_dict = {}
Loc_Ref_Dict_All_Ch = {}
incidence_matrcies = {}
loosened_groups_for_deadlock_dict = {}
jaccard_thresholds = [0.6]*2

In [113]:
update_location_hierarchy_and_refs(
                                channels=[0],
                                jaccard_thresholds=jaccard_thresholds,
                                data_handler=data_handler,
                                Sim_Matrix_dict=Sim_Matrix_dict,
                                agg_models_dict=agg_models_dict,
                                location_groups_dict=location_groups_dict,
                                Loc_Ref_Dict_All_Ch=Loc_Ref_Dict_All_Ch,
                                incidence_matrcies = incidence_matrcies,
    loosened_groups_for_deadlock_dict = loosened_groups_for_deadlock_dict
                                   )

data_handler = DataHandler(samples, verbose=False)

ch 0
here
Unique groups [1 2 3] 


[[2. 0. 2.]
 [0. 1. 0.]
 [2. 0. 3.]]
[1, 3]
optimal gates:
(1, 0, 0.0) [1.0181502129482474, 4.418351903999745]
(2, 3, 0.0) [1.7787638836496742, 5.988442074200048]
(3, 0, 0.0) [-2.629982851409088, 1.0181502129482474]
constraints [[1, 3]]
iter 0 [[1, 3]]


In [516]:
plt.figure()
sns.heatmap(1-Sim_Matrix_dict[0], cmap='Blues', annot=False)

<AxesSubplot:>

In [522]:
dendrogram = plot_gates_dendrogram(agg_models_dict[0], ch='', jacc_threshold=.6,show_title=False, gatefontsize=30 ,yfontsize=30)

None


In [620]:

plt.figure()
plot_gate_as_tiles(data_handler,0,Loc_Ref_Dict_All_Ch=None, rev=1, shift_color =5,color_tiles=False, show_ref=False, tight=True, show_num=True)
plt.axis(False)
plt.figure()
plot_gate_as_tiles(data_handler,0,Loc_Ref_Dict_All_Ch=None, rev=1, shift_color =5,color_tiles=False, show_ref=False, tight=False, show_num=True)
plt.axis(False)
plt.figure()
plot_gate_as_tiles(data_handler,0,Loc_Ref_Dict_All_Ch, rev=1, shift_color =3,color_tiles=True, show_ref=False, tight=True, show_num=True)
plt.axis(False)
plt.figure()
plot_gate_as_tiles(data_handler,0,Loc_Ref_Dict_All_Ch, rev=1, shift_color =3,color_tiles=True, show_ref=True, tight=True, show_num=True)
plt.axis(False)

(-0.975887701278414, 5.04517774042261, -0.15000000000000002, 3.15)

In [619]:
plot_network_graph(0, incidence_matrcies[0])

[[0, 0], [0, 2], [1, 1], [2, 2]]


In [624]:
samples.reverse()

In [625]:
plotted_lr = []
samples_pds = {}
counter = 0
color_by_location = False
for sh, samp in enumerate(samples):
    shift = sh*.47
    gates =[g for g in  samp.gates[0]]
    kde = sns._statistics.KDE(bw_method=.3)
    pd, t = kde(x1=samp(0).flatten())
    samples_pds[sh]= [t, pd]
    for k, gate in enumerate(gates):
        seg = gate.gate
        ind = np.logical_and(t>= seg[0], t<= seg[1])
        tt = t[ind]
        ppd = pd[ind]
        m = 1 if len(gates)>1 else .5
        print(gate.location_group)
        lg = gate.location_group
        gate_num = counter
        counter+=1
        amx = np.argmax(ppd)
        plt.text(tt[amx],m*ppd.min()+shift+.1, f'{gate_num}' ,color='w', fontsize=12)
        col = colors[lg+3] if color_by_location else colors[k+5]
        if lg not in plotted_lr:
            plt.fill_between(tt, m*ppd+shift, shift, color = col, label=f'Location Group: {len(plotted_lr)}')
            plotted_lr+=[lg]
        else:
            plt.fill_between(tt, m*ppd+shift,shift, color = col)

plt.axis(False)
if color_by_location:
    plt.legend(loc='upper left')

3
1
3
1
3
2


In [152]:
from ..cyto.segmentation import *
from skimage.segmentation import watershed

In [251]:
print(colors)

['blue', 'orange', 'g', 'r', 'coral', 'cyan', 'm', 'steelblue', 'brown', 'y', 'gray', 'k']


In [428]:
fill_colors = ['slateblue', 'lightskyblue','cyan', 'cornflowerblue']
z = np.random.normal(0,.31, [2,8000])
z = np.concatenate([z,z+1.7, z+4.6, z[:,:500]+8], axis=1)
kde = sns._statistics.KDE(bw_method=.3)
pd, t = kde(x1=z.flatten())

plt.figure()
plt.plot(t, pd)
plt.scatter(z[0,:], np.random.uniform(-.002,.008,z.shape[1]), s=.001,c='b')
plt.scatter(np.random.uniform(-2,9,1000), np.random.uniform(-.002,.008, 1000),c='b', s=.001)
plt.axis(False)
plt.figure()
plt.plot(t, -pd)
plt.axis(False)

pd_s = watershed(-pd)
wl = get_watershed_lines_from_labeled_segs(pd_s, t)
# wl[1] = wl[1]-.02
segs = convert_watershed_lines_to_gate(wl)
print(segs)
inds = [np.argmin(np.abs(t-l)) for l in wl]
wl_ys = -pd[inds][1:-1]
for j, v in enumerate(wl_ys):
    plt.figure()
    plt.axis(False)
    plt.plot(t, -pd)
    plt.axhline(v, )
    for k, seg in enumerate(segs):
        ind = np.logical_and(t>= seg[0], t<= seg[1])
        tt = t[ind]
        ppd = pd[ind]
        fill_curve = deepcopy(-ppd)
        fill_curve[fill_curve<v] = v
        plt.fill_between(tt, -ppd,fill_curve, color = fill_colors[k])
    # if j<len(wl_ys):
    for jj in range(j+1):
        plt.plot([segs[jj][1]]*10,np.linspace(wl_ys[jj],0.01,10), color='k', linestyle ='--')

[[-3.0134043921465006, 0.8973535618827131], [0.8973535618827131, 3.2019073562213567], [3.2019073562213567, 6.83332545639134], [6.83332545639134, 10.88375333735017]]


In [397]:
markers = ['s','^','o','x']
def plot_segments_pd(t, pd, segs, shift_color=0):
    plt.figure()
    for i, seg in enumerate(segs):
        ind = np.logical_and(t>= seg[0], t<= seg[1])
        tt = t[ind]
        ppd = pd[ind]
        plt.fill_between(tt, ppd, color= fill_colors[i+shift_color], linestyle='-', label =f'Segment {i}')
    plt.legend(loc='upper right')
    plt.axis(False)
    return plt.gca()

In [394]:
plot_segments_pd(t, pd, segs)

<AxesSubplot:>

In [395]:
pd_sa = non_maximum_suppression(pd, pd_s,.1)
pd_sa = merge(pd_sa)
wl_a = get_watershed_lines_from_labeled_segs(pd_sa, t)
segs_a = convert_watershed_lines_to_gate(wl_a)
plot_segments_pd(t,pd, segs_a)

<AxesSubplot:>

In [427]:
pd_swd = suppress_and_merge_tiny_basins(pd,pd_sa, .2,.2)
wl_wd = get_watershed_lines_from_labeled_segs(pd_swd, t)
segs_wd = convert_watershed_lines_to_gate(wl_wd)
plot_segments_pd(t,pd, segs_wd,shift_color=1)


width 0.1 depth 0.10085444637840238 width_cond True
width 0.215 depth 0.7810054676495543 width_cond False


<AxesSubplot:>